cleaning:
  cols_to_remove: []
  cols_to_transform:
    family_history_with_overweight: {"yes": 1, "no": 0}
    Gender: {"Male": 0, "Female": 1}
    FAVC: {"yes": 1, "no": 0}
    SMOKE: {"yes": 1, "no": 0}
    SCC: {"yes": 1, "no": 0}
    CAEC: {"no": 0, "Sometimes": 1, "Frequently": 2, "Always": 3}
    CALC: {"no": 0, "Sometimes": 1, "Frequently": 2, "Always": 3}
    MTRANS: {"Public_Transportation": 0, "Walking": 1, "Automobile": 2, "Motorbike": 3, "Bike": 4}
  cols_to_normalize:
    - Age
    - Height
    - Weight
    - FCVC
    - NCP
    - CH2O
    - FAF
    - TUE

splitting:
  train_ratio: 0.8
  test_ratio: 0.15
  validation_ratio: 0.05
  seed: 50

model:
  type: "RandomForestClassifier"
  random_state: 42
  target_column: "NObeyesdad"
  n_estimators: 100
  max_iter: 1000

model_selection:
  method: "autogluon" # "manual/autogluon"

deployment:
  model_filepath: "data/models/champion_model.pkl"
  metrics_filepath: "data/models/champion_metrics.pkl"

use_synthetic_data: false

syn_num_rows: 1000  # Number of synthetic rows to generate
